### ISSUE TITLE
Could you add a license?

### ISSUE THREAD

**Issue by ScienceMarc** [tomstewart89/Vector#3]
This library does not have a license associated with it. Could you add one to clarify what we are allowed to do?

I noticed many of your projects have the MIT license. Did you forget to add one to this project?

Thanks.

**Comment by tomstewart89** [comment]
Hey @ScienceMarc, I've given the library an MIT license so feel free to use it however you like, enjoy!

**Comment by ScienceMarc** [comment]
Thanks
