### ISSUE TITLE
Miss part of data

### ISSUE THREAD

**Issue by TimonPeng** [tomstewart89/Vector#4]
I push a uint8_t to the vector, but miss some data when i try to read it.

```
#include <Vector.h>

Vector<uint8_t *> vector;

void setup()
{
    Serial.begin(115200);

    uint8_t v[] = {0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07, 0x08, 0x09};
    vector.PushBack(v);

    for (int i = 0; i < vector.Size(); i++)
    {
        uint8_t *e = vector[i];
        Serial.println(sizeof(e));
        // print 4

        for (int j = 0; j < sizeof(e); j++)
        {
            Serial.printf("%02x", e[j]);
        }
        // print 01020304
    }
}

void loop()
{
}

```

**Comment by tomstewart89** [comment]
Hey @TimonPeng, thanks for your interest in my repo! Regarding your question though, there's a bunch of problems with that example code you attached that are probably the reason you're having problems.

Have a look at the BasicUseage example and try to take it from there. Good luck!

**Comment by TimonPeng** [comment]
What's the problem? What is the difference with example? Thank you. @tomstewart89

**Comment by TimonPeng** [comment]
I know the problem, cheers!
